# Use the official PostgreSQL image from Docker Hub
FROM postgres:16

# Set environment variables for default user and database
ENV POSTGRES_USER=iec
ENV POSTGRES_PASSWORD=123456789@
ENV POSTGRES_DB=event_db

# Expose PostgreSQL default port
EXPOSE 5432
